### ISSUE TITLE
Uzupełnienie README.md

### ISSUE THREAD

**Issue by evilbc** [evilbc/biznes-elektroniczny#1]
Repozytorium zawiera plik README.md z opisem projektu, wykorzystanej
wersji oprogramowania, sposobu uruchomienia i składu zespołu.

**Comment by MichalNiesyto** [comment]
Do dodania również informacje o VOLUMES z docker inspect. Zgodnie z ostatnim PR.

**Comment by evilbc** [comment]
Wersja oprogramowania - do sprawdzenia biblioteki użyte w scraperze, inicjalizacji produktów, testach i docker-compose
