### ISSUE TITLE
Powiadomienia

### ISSUE THREAD

**Issue by MichalNiesyto** [evilbc/biznes-elektroniczny#16]
# Poprawnie skonfigurowano mechanizm wysyłania powiadomień e-mail ze sklepu. Przykładowo klient powinien otrzymać wiadomość po rejestracji lub po dokonaniu zakupów.

Proponuję zainstalować własny serwer pocztowy jako kontener.

## Mailcatcher
Tutaj mamy serwer w którym odbieramy wszystkie maile jako jedno konto i w przeglądarce widać tą pocztę (widać nadawcę i odbiorcę).
https://mailcatcher.me

## Postfix + klient pocztowy w przeglądarce
Tutaj mamy normalną pocztę - każdy użytkownik musi się logować osobno + rejestracja.
Bardziej skomplikowane. 

## Rzeczywiste wysyłanie poczty

Konfiguracja w oparciu o rzeczywisty serwer SMTP. Trzeba uważać na sekrety (hasło do poczty).

Osobiście preferuję opcję 1. Proszę o feedback.

**Comment by evilbc** [comment]
Czy PrestaShop już nie ma jakoś w sobie wysyłania maili? https://devdocs.prestashop-project.org/8/development/mail/
Ale jeśli uważasz, że to 1 jest łatwiejsze, to można tym

**Comment by evilbc** [comment]
https://docs.prestashop-project.org/1.7-documentation/user-guide/configuring-shop/advanced-parameters/email
Use PHP's mail() function. This option is recommended by default. In the event that this does not work, then use the SMPT option below.
To chyba powinno działać? 
Preferencje -> klienci -> Wyślij e-mail po rejestracji
Oraz
Preferencje -> Zamówienia -> Statusy -> nowy -> Wyślij e-mail do klienta, kiedy zmieni się status zamówienia
Chyba wystarczy mieć te 2 ustawienia włączone i tamto z linku?

**Comment by MichalNiesyto** [comment]
Prestashop ma wysyłanie maili, ale trzeba jakoś skonfigurować serwer, który odbierze te maile i wyśle dalej (lub sam je zatrzyma jak mailcatcher).

https://www.php.net/manual/en/mail.configuration.php

Tutaj masz plik php.ini, w którym są domyślne wartości. Wtedy też będziemy widzieć te maile w przeglądarce. A tak wysyła je w próżnię i pewnie w logach widać błędy, bo nie ma serwera SMTP na localhost port 25.

**Comment by MichalNiesyto** [comment]
Więc preferencje to jedno, a kwestia faktycznej wysyłki do drugie.

**Comment by evilbc** [comment]
Spróbowałem się zarejestrować i rzeczywiście maile nie przychodzą, to można użyć tego mailcatchera jeśli jest prostszy

**Comment by MichalNiesyto** [comment]
Kwestię customizacji zawartości zostawiam osobom zajmującym się frontendem

**Comment by evilbc** [comment]
Jeszcze ta customizacja zawartości - @MichalMroz21
