### ISSUE TITLE
Główne wymagania

### ISSUE THREAD

**Issue by evilbc** [evilbc/biznes-elektroniczny#6]
3. *Zespół utworzył sklep wykorzystując rozwiązanie bazowe Prestashop w wersji 1.7.8
- [x] Sklep posiada menu górne, stopkę, wyszukiwarkę, umożliwia logowanie i rejestrację, prezentuje listę produktów i umożliwia ich wybór oraz zakup, dostępne są strony O sklepie, Formy płatności i inne standardowo oferowane strony, dostępne zaraz po instalacji. Możliwe jest przeprowadzenie procesu rejestracji, logowania oraz dostęp do historii zamówień.
- [x] Prezentowany sklep nie posiada domyślnych wartości zdefiniowanych przez kreator w miejscach prezentowanych klientowi.
- [x] Interfejs użytkownika jest języku polskim;
- [x] W sklepie zarejestrowano conajmniej 1000 produktów (chyba że wybrany sklep źródłowy nie oferuje takiej liczby produktów). Część produktów ma być niedostępna. Stany magazynowe proszę ustawić tak, aby liczba dostępnych produktów każdego rodzaju nie przekraczała 10 szt.
- [x] Nazwy, opisy, zdjęcia, ceny i podatki określone dla każdego produktu muszą odpowiadać rzeczywistym danym pobranym ze sklepu źródłowego. Polskie znaki muszą się prawidłowo wyświetlać.
- [x] W sklepie zarejestrowano conajmniej 4 kategorie i w każdej z nich conajmniej 2 podkategorie. Żadna z podkategorii nie może być pusta.
- [x] W sklepie zdefiniowano metody płatności stosowane w Polsce (nie należy przeprowadzać żadnych integracji do zewnętrznych operatorów płatności). Nie mogą występować metody płatności, których nie stosuje się w Polsce.
- [x] Poprawnie skonfigurowano mechanizm wysyłania powiadomień e-mail ze sklepu. Przykładowo klient powinien otrzymać wiadomość po rejestracji lub po dokonaniu zakupów.
- [x] Oferowana w sklepie funkcjonalność działa prawidłowo - tzn. nie generuje błędów (białe strony, 500, 404, 403). Dotyczy to zarówno kodu w plikach PHP, JS jak i referencji do obrazków.
- [x] Należy zdefiniować dwóch nowych przewoźników. Należy dostosować ustawienia przewoźników, tak aby dla zamówień powyżej 2000 zł dostawa powinna być darmowa. Dla produktów cięższych niż 50 kg dostawa powinna być niemożliwa. Opłaty dla przewoźników powinny być różne

Do rozbicia na mniejsze zadania

**Comment by evilbc** [comment]
Podpunkty 4, 5, 6 ja zrobię, pozostałe Maksym/Michał M.

**Comment by MichalNiesyto** [comment]
Powiadomienia rozbite na osobne zadanie

**Comment by evilbc** [comment]
To, co zostało poza powiadomieniami do Maksyma  (nie zaakceptował zaproszenia jeszcze)

**Comment by evilbc** [comment]
Wygląda na to, że już wszystko zrobione - zamykam
