### ISSUE TITLE
Inicjacja kategorii, podkategorii, produktów

### ISSUE THREAD

**Issue by evilbc** [evilbc/biznes-elektroniczny#7]
Zespół utworzył skrypt, który poprzez API sklepu zainicjuje kategorie, podkategorie,
produkty w sklepie na podstawie rezultatów scrapowania,

**Comment by MichalNiesyto** [comment]
Inicjalizacja dobrze działa. Ale dobrze jest przemyśleć sprawę śledzenia postępu, inicjalizacji klucza API, inicjalizacji waluty jako PLN, oraz wymagania uruchomienia scrapera przed inicjalizacją jeżeli nie ma obrazków. 

Być może również przeniesienie klucza API do .env

**Comment by evilbc** [comment]
Zrobione w #24
