### ISSUE TITLE
Modyfikacja standardowego wyglądu sklepu

### ISSUE THREAD

**Issue by evilbc** [evilbc/biznes-elektroniczny#8]
Modyfikacja standardowego wyglądu sklepu:
- [ ] Wygląd sklepu i sposób prezentacji informacji jest zgodny z oferowanym asortymentem lub jest zgodny ze sklepem bazowym (wskazanym jako źródło danych). Layout sklepu i elementy interfejsu użytkownika są wykonane estetycznie, zgodnie z obowiązującymi standardami.
- [ ] Na stronie głównej należy dodać co najmniej jeden działający baner w tematyce sklepu,

**Comment by MichalNiesyto** [comment]
Należy również pamiętać o tym by maile miały spójny wygląd z resztą strony

**Comment by evilbc** [comment]
#16 jest issue na maile

Ale też sprawdzić, czy gdzieś zostało cos po angielsku
